index:
    path: /
    controller: App\Controller\NavController::index

dice:
    path: /dice
    controller: App\Controller\DiceController::GameOf21

yatzy:
    path: /yatzy
    controller: App\Controller\YatzyController::Yatzy

highscore:
    path: /highscore
    controller: App\Controller\HighscoreController::index

new:
    path: /new
    controller: App\Controller\HighscoreController::new